[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Financify Docker CRUD"
authors = [{name = "João Abner", email = "joaoabner@alunos.utfpr.edu.br"}]
dynamic = ["version", "description"]
